export const LOAD_VENUE_DETAIL_REQUEST = 'LOAD_VENUE_DETAIL_REQUEST';
export const LOAD_VENUE_DETAIL_SUCCESS = 'LOAD_VENUE_DETAIL_SUCCESS';
export const LOAD_VENUE_DETAIL_FAILURE = 'LOAD_VENUE_DETAIL_FAILURE';
